// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "StateSmith.h"
#include <stdbool.h>  // pour le type bool si nécessaire
#include <string.h>   // pour memset
// #include "your_header_here.h"

// Ces fonctions doivent être définies dans ton code (par ex. main.cpp) :
void initRedLight(void);
void initYellowLight(void);
void initGreenLight(void);
void turnOnRedLight(void);
void turnOffRedLight(void);
void turnOnYellowLight(void);
void turnOffYellowLight(void);
void turnOnGreenLight(void);
void turnOffGreenLight(void);

// Fonction utilisée lorsqu'on doit sortir jusqu'à un état donné.
static void exit_up_to_state_handler(StateSmith* sm, StateSmith_StateId desired_state);

static void ROOT_enter(StateSmith* sm);

static void TRAFFICLIGHTGREEN_enter(StateSmith* sm);
static void TRAFFICLIGHTGREEN_exit(StateSmith* sm);
static void TRAFFICLIGHTGREEN_tick(StateSmith* sm);

static void TRAFFICLIGHTSTATERED_enter(StateSmith* sm);
static void TRAFFICLIGHTSTATERED_exit(StateSmith* sm);
static void TRAFFICLIGHTSTATERED_requestgreen(StateSmith* sm);
static void TRAFFICLIGHTSTATERED_tick(StateSmith* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_enter(StateSmith* sm);
static void TRAFFICLIGHTSTATEREDYELLOW_exit(StateSmith* sm);
static void TRAFFICLIGHTSTATEREDYELLOW_tick(StateSmith* sm);

static void TRAFFICLIGHTYELLOW_enter(StateSmith* sm);
static void TRAFFICLIGHTYELLOW_exit(StateSmith* sm);
static void TRAFFICLIGHTYELLOW_tick(StateSmith* sm);

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void StateSmith_ctor(StateSmith* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void StateSmith_start(StateSmith* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: LCA = ROOT, rien à faire.

        // Step 2: Transition action:
        // uml: / { initRedLight(), initYellowLight(), initGreenLight() } TransitionTo(TrafficLightStateRed)
        initRedLight();
        initYellowLight();
        initGreenLight();

        // Step 3: entrer dans TrafficLightStateRed
        TRAFFICLIGHTSTATERED_enter(sm);

        // Step 4: fin de la transition
        return;
    }
}

// Dispatches an event to the state machine. Not thread safe.
void StateSmith_dispatch_event(StateSmith* sm, StateSmith_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: ROOT
        case StateSmith_StateId_ROOT:
            // Aucun event géré ici.
            break;

        // STATE: TrafficLightGreen
        case StateSmith_StateId_TRAFFICLIGHTGREEN:
            switch (event_id)
            {
                case StateSmith_EventId_TICK:
                    TRAFFICLIGHTGREEN_tick(sm);
                    break;

                default:
                    break;
            }
            break;

        // STATE: TrafficLightStateRed
        case StateSmith_StateId_TRAFFICLIGHTSTATERED:
            switch (event_id)
            {
                case StateSmith_EventId_TICK:
                    TRAFFICLIGHTSTATERED_tick(sm);
                    break;
                case StateSmith_EventId_REQUESTGREEN:
                    TRAFFICLIGHTSTATERED_requestgreen(sm);
                    break;

                default:
                    break;
            }
            break;

        // STATE: TrafficLightStateRedYellow
        case StateSmith_StateId_TRAFFICLIGHTSTATEREDYELLOW:
            switch (event_id)
            {
                case StateSmith_EventId_TICK:
                    TRAFFICLIGHTSTATEREDYELLOW_tick(sm);
                    break;

                default:
                    break;
            }
            break;

        // STATE: TrafficLightYellow
        case StateSmith_StateId_TRAFFICLIGHTYELLOW:
            switch (event_id)
            {
                case StateSmith_EventId_TICK:
                    TRAFFICLIGHTYELLOW_tick(sm);
                    break;

                default:
                    break;
            }
            break;
    }
}

// Quitter jusqu'à un état commun
static void exit_up_to_state_handler(StateSmith* sm, StateSmith_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case StateSmith_StateId_TRAFFICLIGHTGREEN:
                TRAFFICLIGHTGREEN_exit(sm);
                break;

            case StateSmith_StateId_TRAFFICLIGHTSTATERED:
                TRAFFICLIGHTSTATERED_exit(sm);
                break;

            case StateSmith_StateId_TRAFFICLIGHTSTATEREDYELLOW:
                TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
                break;

            case StateSmith_StateId_TRAFFICLIGHTYELLOW:
                TRAFFICLIGHTYELLOW_exit(sm);
                break;

            default:
                return;  // sécurité
        }
    }
}

////////////////////////////////////////////////////////////////////////////////
// ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(StateSmith* sm)
{
    sm->state_id = StateSmith_StateId_ROOT;
}

////////////////////////////////////////////////////////////////////////////////
// TrafficLightGreen
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTGREEN_enter(StateSmith* sm)
{
    sm->state_id = StateSmith_StateId_TRAFFICLIGHTGREEN;

    // uml: enter / { turnOnGreenLight(), time = 0 }
    turnOnGreenLight();
    sm->vars.time = 0;
}

static void TRAFFICLIGHTGREEN_exit(StateSmith* sm)
{
    // uml: exit / { turnOffGreenLight() }
    turnOffGreenLight();

    sm->state_id = StateSmith_StateId_ROOT;
}

static void TRAFFICLIGHTGREEN_tick(StateSmith* sm)
{
    // uml: tick / { time++ }
    sm->vars.time++;

    // uml: tick [time > 5000] TransitionTo(TrafficLightYellow)
    if (sm->vars.time > 5000)
    {
        TRAFFICLIGHTGREEN_exit(sm);
        TRAFFICLIGHTYELLOW_enter(sm);
        return;
    }
}

////////////////////////////////////////////////////////////////////////////////
// TrafficLightStateRed
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATERED_enter(StateSmith* sm)
{
    sm->state_id = StateSmith_StateId_TRAFFICLIGHTSTATERED;

    // uml: enter / { turnOnRedLight(), time = 0 }
    turnOnRedLight();
    sm->vars.time = 0;
}

static void TRAFFICLIGHTSTATERED_exit(StateSmith* sm)
{
    // uml: exit / { turnOffRedLight() }
    turnOffRedLight();

    sm->state_id = StateSmith_StateId_ROOT;
}

static void TRAFFICLIGHTSTATERED_requestgreen(StateSmith* sm)
{
    // uml: requestGreen TransitionTo(TrafficLightStateRedYellow)
    TRAFFICLIGHTSTATERED_exit(sm);
    TRAFFICLIGHTSTATEREDYELLOW_enter(sm);
}

static void TRAFFICLIGHTSTATERED_tick(StateSmith* sm)
{
    // uml: tick / { time++ }
    sm->vars.time++;
}

////////////////////////////////////////////////////////////////////////////////
// TrafficLightStateRedYellow
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATEREDYELLOW_enter(StateSmith* sm)
{
    sm->state_id = StateSmith_StateId_TRAFFICLIGHTSTATEREDYELLOW;

    // uml: enter / { turnOnRedLight(), turnOnYellowLight(), time = 0 }
    turnOnRedLight();
    turnOnYellowLight();
    sm->vars.time = 0;
}

static void TRAFFICLIGHTSTATEREDYELLOW_exit(StateSmith* sm)
{
    // uml: exit / { turnOffRedLight(), turnOffYellowLight() }
    turnOffRedLight();
    turnOffYellowLight();

    sm->state_id = StateSmith_StateId_ROOT;
}

static void TRAFFICLIGHTSTATEREDYELLOW_tick(StateSmith* sm)
{
    // uml: tick / { time++ }
    sm->vars.time++;

    // uml: tick [time > 2000] TransitionTo(TrafficLightGreen)
    if (sm->vars.time > 2000)
    {
        TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
        TRAFFICLIGHTGREEN_enter(sm);
        return;
    }
}

////////////////////////////////////////////////////////////////////////////////
// TrafficLightYellow
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTYELLOW_enter(StateSmith* sm)
{
    sm->state_id = StateSmith_StateId_TRAFFICLIGHTYELLOW;

    // uml: enter / { turnOnYellowLight(), time = 0 }
    turnOnYellowLight();
    sm->vars.time = 0;
}

static void TRAFFICLIGHTYELLOW_exit(StateSmith* sm)
{
    // uml: exit / { turnOffYellowLight() }
    turnOffYellowLight();

    sm->state_id = StateSmith_StateId_ROOT;
}

static void TRAFFICLIGHTYELLOW_tick(StateSmith* sm)
{
    // uml: tick / { time++ }
    sm->vars.time++;

    // uml: tick [time > 3000] TransitionTo(TrafficLightStateRed)
    if (sm->vars.time > 3000)
    {
        TRAFFICLIGHTYELLOW_exit(sm);
        TRAFFICLIGHTSTATERED_enter(sm);
        return;
    }
}

// Thread safe.
char const * StateSmith_state_id_to_string(StateSmith_StateId id)
{
    switch (id)
    {
        case StateSmith_StateId_ROOT:                   return "ROOT";
        case StateSmith_StateId_TRAFFICLIGHTGREEN:      return "TRAFFICLIGHTGREEN";
        case StateSmith_StateId_TRAFFICLIGHTSTATERED:   return "TRAFFICLIGHTSTATERED";
        case StateSmith_StateId_TRAFFICLIGHTSTATEREDYELLOW: return "TRAFFICLIGHTSTATEREDYELLOW";
        case StateSmith_StateId_TRAFFICLIGHTYELLOW:     return "TRAFFICLIGHTYELLOW";
        default:                                        return "?";
    }
}

// Thread safe.
char const * StateSmith_event_id_to_string(StateSmith_EventId id)
{
    switch (id)
    {
        case StateSmith_EventId_REQUESTGREEN: return "REQUESTGREEN";
        case StateSmith_EventId_TICK:         return "TICK";
        default:                              return "?";
    }
}
