// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once
#include <stdint.h>

typedef enum StateSmith_EventId
{
    StateSmith_EventId_REQUESTGREEN = 0,
    StateSmith_EventId_TICK = 1
} StateSmith_EventId;

enum
{
    StateSmith_EventIdCount = 2
};

typedef enum StateSmith_StateId
{
    StateSmith_StateId_ROOT = 0,
    StateSmith_StateId_TRAFFICLIGHTGREEN = 1,
    StateSmith_StateId_TRAFFICLIGHTSTATERED = 2,
    StateSmith_StateId_TRAFFICLIGHTSTATEREDYELLOW = 3,
    StateSmith_StateId_TRAFFICLIGHTYELLOW = 4
} StateSmith_StateId;

enum
{
    StateSmith_StateIdCount = 5
};

// Variables de la machine à états
typedef struct StateSmith_Vars
{
    uint32_t time;   // utilisé pour les temporisations (ms)
} StateSmith_Vars;

// Déclaration de la struct principale
typedef struct StateSmith StateSmith;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void StateSmith_ctor(StateSmith* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void StateSmith_start(StateSmith* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void StateSmith_dispatch_event(StateSmith* sm, StateSmith_EventId event_id);

// Thread safe.
char const * StateSmith_state_id_to_string(StateSmith_StateId id);

// Thread safe.
char const * StateSmith_event_id_to_string(StateSmith_EventId id);

// Définition de la struct StateSmith
struct StateSmith
{
    // Etat courant
    StateSmith_StateId state_id;

    // Variables
    StateSmith_Vars vars;
};
