// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "TrafficLight.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"

// Externe Deklarationen für Aktionen und Guard-Variable
extern bool requestGreen;

void turnOnRedLigth(void);
void turnOffRedLigth(void);
void turnOnRedLight(void);
void turnOffRedLight(void);
void turnOnYellowLight(void);
void turnOffYellowLight(void);
void turnOnGreenLight(void);
void turnOffGreenLight(void);


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TrafficLight* sm, TrafficLight_StateId desired_state);

static void ROOT_enter(TrafficLight* sm);

static void TRAFFICLIGHTGREEN_enter(TrafficLight* sm);

static void TRAFFICLIGHTGREEN_exit(TrafficLight* sm);

static void TRAFFICLIGHTGREEN_tick(TrafficLight* sm);

static void TRAFFICLIGHTSTATERED_enter(TrafficLight* sm);

static void TRAFFICLIGHTSTATERED_exit(TrafficLight* sm);

static void TRAFFICLIGHTSTATERED_tick(TrafficLight* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_enter(TrafficLight* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_exit(TrafficLight* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_tick(TrafficLight* sm);

static void TRAFFICLIGHTYELLOW_enter(TrafficLight* sm);

static void TRAFFICLIGHTYELLOW_exit(TrafficLight* sm);

static void TRAFFICLIGHTYELLOW_tick(TrafficLight* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TrafficLight_ctor(TrafficLight* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TrafficLight_start(TrafficLight* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(TrafficLightStateRed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
            TRAFFICLIGHTSTATERED_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TrafficLight_dispatch_event(TrafficLight* sm, TrafficLight_EventId event_id)
{
    // This state machine design only has a single event type so we can safely assume
    // that the dispatched event is `tick` without checking the `event_id` parameter.
    (void)event_id; // This line prevents an 'unused variable' compiler warning
    
    switch (sm->state_id)
    {
        // STATE: TrafficLight
        case TrafficLight_StateId_ROOT:
            // state and ancestors have no handler for `tick` event.
            break;
        
        // STATE: TrafficLightGreen
        case TrafficLight_StateId_TRAFFICLIGHTGREEN:
            TRAFFICLIGHTGREEN_tick(sm); 
            break;
        
        // STATE: TrafficLightStateRed
        case TrafficLight_StateId_TRAFFICLIGHTSTATERED:
            TRAFFICLIGHTSTATERED_tick(sm); 
            break;
        
        // STATE: TrafficLightStateRedYellow
        case TrafficLight_StateId_TRAFFICLIGHTSTATEREDYELLOW:
            TRAFFICLIGHTSTATEREDYELLOW_tick(sm); 
            break;
        
        // STATE: TrafficLightYellow
        case TrafficLight_StateId_TRAFFICLIGHTYELLOW:
            TRAFFICLIGHTYELLOW_tick(sm); 
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TrafficLight* sm, TrafficLight_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case TrafficLight_StateId_TRAFFICLIGHTGREEN: TRAFFICLIGHTGREEN_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTSTATERED: TRAFFICLIGHTSTATERED_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTSTATEREDYELLOW: TRAFFICLIGHTSTATEREDYELLOW_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTYELLOW: TRAFFICLIGHTYELLOW_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTGREEN
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTGREEN_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTGREEN;
    
    // TrafficLightGreen behavior
    // uml: enter / { turnOnGreenLight(); }
    {
        // Step 1: execute action `turnOnGreenLight();`
        turnOnGreenLight();
    } // end of behavior for TrafficLightGreen
}

static void TRAFFICLIGHTGREEN_exit(TrafficLight* sm)
{
    // TrafficLightGreen behavior
    // uml: exit / { turnOffGreenLight(); }
    {
        // Step 1: execute action `turnOffGreenLight();`
        turnOffGreenLight();
    } // end of behavior for TrafficLightGreen
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTGREEN_tick(TrafficLight* sm)
{
    // TrafficLightGreen behavior
    // uml: tick TransitionTo(TrafficLightYellow)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTGREEN_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightYellow`.
        TRAFFICLIGHTYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightGreen
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATERED
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATERED_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTSTATERED;
    
    // TrafficLightStateRed behavior
    // uml: enter / { turnOnRedLigth(); }
    {
        // Step 1: execute action `turnOnRedLigth();`
        turnOnRedLigth();
    } // end of behavior for TrafficLightStateRed
}

static void TRAFFICLIGHTSTATERED_exit(TrafficLight* sm)
{
    // TrafficLightStateRed behavior
    // uml: exit / { turnOffRedLigth(); }
    {
        // Step 1: execute action `turnOffRedLigth();`
        turnOffRedLigth();
    } // end of behavior for TrafficLightStateRed
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTSTATERED_tick(TrafficLight* sm)
{
    // TrafficLightStateRed behavior
    // uml: tick [requestGreen] TransitionTo(TrafficLightStateRedYellow)
    if (requestGreen)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATERED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRedYellow`.
        TRAFFICLIGHTSTATEREDYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATEREDYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATEREDYELLOW_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTSTATEREDYELLOW;
    
    // TrafficLightStateRedYellow behavior
    // uml: enter / { turnOnRedLight(), turnOnYellowLight() }
    {
        // Step 1: execute action `turnOnRedLight(), turnOnYellowLight()`
        turnOnRedLight();
        turnOnYellowLight();
    } // end of behavior for TrafficLightStateRedYellow
}

static void TRAFFICLIGHTSTATEREDYELLOW_exit(TrafficLight* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: exit / { turnOffRedLight(), turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffRedLight(), turnOffYellowLight()`
        turnOffRedLight();
        turnOffYellowLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTSTATEREDYELLOW_tick(TrafficLight* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: tick TransitionTo(TrafficLightGreen)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightGreen`.
        TRAFFICLIGHTGREEN_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRedYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTYELLOW_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTYELLOW;
    
    // TrafficLightYellow behavior
    // uml: enter / { turnOnYellowLight() }
    {
        // Step 1: execute action `turnOnYellowLight()`
        turnOnYellowLight();
    } // end of behavior for TrafficLightYellow
}

static void TRAFFICLIGHTYELLOW_exit(TrafficLight* sm)
{
    // TrafficLightYellow behavior
    // uml: exit / { turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffYellowLight()`
        turnOffYellowLight();
    } // end of behavior for TrafficLightYellow
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTYELLOW_tick(TrafficLight* sm)
{
    // TrafficLightYellow behavior
    // uml: tick TransitionTo(TrafficLightStateRed)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightYellow
    
    // No ancestor handles this event.
}

// Thread safe.
char const * TrafficLight_state_id_to_string(TrafficLight_StateId id)
{
    switch (id)
    {
        case TrafficLight_StateId_ROOT: return "ROOT";
        case TrafficLight_StateId_TRAFFICLIGHTGREEN: return "TRAFFICLIGHTGREEN";
        case TrafficLight_StateId_TRAFFICLIGHTSTATERED: return "TRAFFICLIGHTSTATERED";
        case TrafficLight_StateId_TRAFFICLIGHTSTATEREDYELLOW: return "TRAFFICLIGHTSTATEREDYELLOW";
        case TrafficLight_StateId_TRAFFICLIGHTYELLOW: return "TRAFFICLIGHTYELLOW";
        default: return "?";
    }
}

// Thread safe.
char const * TrafficLight_event_id_to_string(TrafficLight_EventId id)
{
    switch (id)
    {
        case TrafficLight_EventId_TICK: return "TICK";
        default: return "?";
    }
}
