// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum TrafficLight_EventId
{
    TrafficLight_EventId_TICK = 0
} TrafficLight_EventId;

enum
{
    TrafficLight_EventIdCount = 1
};

typedef enum TrafficLight_StateId
{
    TrafficLight_StateId_ROOT = 0,
    TrafficLight_StateId_TRAFFICLIGHTGREEN = 1,
    TrafficLight_StateId_TRAFFICLIGHTSTATERED = 2,
    TrafficLight_StateId_TRAFFICLIGHTSTATEREDYELLOW = 3,
    TrafficLight_StateId_TRAFFICLIGHTYELLOW = 4
} TrafficLight_StateId;

enum
{
    TrafficLight_StateIdCount = 5
};


// Generated state machine
// forward declaration
typedef struct TrafficLight TrafficLight;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct TrafficLight_Vars
{
    uint16_t count; // this var can be referenced in diagram
} TrafficLight_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TrafficLight_ctor(TrafficLight* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TrafficLight_start(TrafficLight* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TrafficLight_dispatch_event(TrafficLight* sm, TrafficLight_EventId event_id);

// Thread safe.
char const * TrafficLight_state_id_to_string(TrafficLight_StateId id);

// Thread safe.
char const * TrafficLight_event_id_to_string(TrafficLight_EventId id);

// Generated state machine
struct TrafficLight
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TrafficLight_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    TrafficLight_Vars vars;
};

